- config/strategy-config-eth.js
- contracts/eth/enums/ProtocolEnum.sol
- contracts/eth/strategies/yearn/v2/YearnV2BaseStrategy.sol
- contracts/eth/strategies/yearn/v2/YearnV2YETHStrategy.sol
- test/strategy-eth/yearn/v2/yearn-v2-yeth-strategy-checker.js
> feat: yearn eth strategy

- package.json
- scripts/uniswap-v3-swap.js
add uniswap-v3-swap utils to test
> add uniswap-v3-swap utils to test

- scripts/uniswap-v3-swap.js
add uniswap-v3-swap ethi utils to test
> add uniswap-v3-swap ethi utils to test

- contracts/eth/vault/ETHVault.sol
- package.json
Hotfix/v1.5.10 fix vault end adjust position
> fix vault endAdjustPosition

- contracts/eth/strategies/stakewise/StakeWiseEthSeth23000Strategy.sol
- contracts/eth/strategies/stakewise/StakeWiseReth2Seth2500Strategy.sol
- contracts/eth/strategies/uniswapv3/ETHUniswapV3BaseStrategy.sol
- contracts/usd/strategies/uniswapv3/UniswapV3Strategy.sol
- contracts/utils/actions/UniswapV3LiquidityActionsMixin.sol
uniswapV3 add collect method for unrealized apy calculate;
reduce code;
bug fix;
> uniswapV3 stakeWise optimize

- config/strategy-usd/strategy-config-usd.js
- hardhat.config.js
> remove strategy

- contracts/eth/strategies/stakewise/StakeWiseReth2Seth2500Strategy.sol
> stake wise params

- contracts/eth/vault/ETHVault.sol
- contracts/eth/vault/IETHVault.sol
- test/vault-eth/vault-test.js
> add vault multicall

- scripts/mainnet-grow.js
- test/vault-usd/vault-split-old-new-user.test.js
> remove synthetix modifier

- contracts/eth/vault/ETHVault.sol
- contracts/eth/vault/IETHVault.sol
- package.json
> remove multicall

- hardhat.config.js
> modify blocknum

- config/strategy-usd/strategy-config-usd-convex.js
- config/strategy-usd/strategy-config-usd.js
remove stargate and convexmetamim
> remove stargate and convexmetamim

- package.json
- scripts/uniswap-v3-increase-observation.js
add uniswap-v3-increase-observation.js for fork test
> add uniswap-v3-increase-observation.js for fork test

- hardhat.config.js
modify hardhat.config make query history
> modify hardhat.config make query history

- contracts/eth/mock/Mock3CoinStrategy.sol
- contracts/eth/mock/MockVault.sol
- contracts/eth/strategies/ETHBaseClaimableStrategy.sol
- contracts/eth/strategies/ETHBaseStrategy.sol
- contracts/eth/strategies/IETHStrategy.sol
- contracts/eth/vault/ETHVault.sol
- contracts/eth/vault/ETHVaultStorage.sol
- contracts/eth/vault/IETHVault.sol
- contracts/usd/strategies/aura/Aura3PoolStrategy.sol
- contracts/usd/strategies/convex/ib-usdc/ConvexIBUsdcStrategy.sol
- contracts/usd/strategies/convex/ib/ConvexIBUsdtStrategy.sol
- hardhat.config.js
- package.json
- scripts/uniswap-v3-increase-observation.js
- test/strategy-eth/strategy-checker.js
- test/strategy-usd/strategy-checker.js
> merge v1.5.10 to v1.6.0

- contracts/eth/strategies/stakewise/StakeWiseEthSeth23000Strategy.sol
- contracts/eth/strategies/stakewise/StakeWiseReth2Seth2500Strategy.sol
- contracts/eth/strategies/uniswapv3/ETHUniswapV3BaseStrategy.sol
- contracts/usd/strategies/uniswapv3/UniswapV3Strategy.sol
skakeWise & uniswapV3 claim report
> skakeWise & uniswapV3 claim report

- scripts/deploy.js
> fix deploy script bug

- hardhat.config.js
- package.json
modify blocknum and upgrade core version
> modify blocknum and upgrade core version

- contracts/eth/vault/ETHVault.sol
- package.json
> fix new and old asset bug

- contracts/eth/strategies/ETHBaseStrategy.sol
- contracts/eth/strategies/convex/ConvexBaseStrategy.sol
- contracts/usd/strategies/convex/ib-usdc/ConvexIBUsdcStrategy.sol
- contracts/usd/strategies/convex/ib/ConvexIBUsdtStrategy.sol
> refactor: optimize code after code review

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/testcases.yml
- package.json
1. add cicd script
2. add pr template
> chore: add cicd for contracts compile

- config/strategy-eth/strategy-config-eth-convex.js
- config/strategy-usd/strategy-config-usd-convex.js
- hardhat.config.js
modify blocknumber and strategy config
1、modify blocknum=15384114
2、remove strategy ConvexMetaTusdStrategy、ConvexPaxStrategy、ConvexUsdtStrategy、ConvexSETHStrategy
> modify blocknumber and strategy config

- contracts/eth/strategies/stakewise/StakeWiseEthSeth23000Strategy.sol
- contracts/eth/strategies/stakewise/StakeWiseReth2Seth2500Strategy.sol
- contracts/eth/strategies/uniswapv3/ETHUniswapV3BaseStrategy.sol
- contracts/usd/strategies/uniswapv3/UniswapV3Strategy.sol
- contracts/utils/actions/UniswapV3LiquidityActionsMixin.sol
downsizing contracts stakeWise & uniswapV3;
stakeWise swapRewardsToWants emit
> stakeWise emit and downsizing

- contracts/eth/strategies/stakewise/StakeWiseEthSeth23000Strategy.sol
- contracts/eth/strategies/stakewise/StakeWiseReth2Seth2500Strategy.sol
- contracts/eth/strategies/uniswapv3/ETHUniswapV3BaseStrategy.sol
downsizing contracts stakeWise & uniswapV3
> downsizing contracts stakeWise & uniswapV3

- config/strategy-eth/strategy-config-eth-convex.js
- contracts/eth/vault/ETHVault.sol
- contracts/eth/vault/ETHVaultAdmin.sol
- contracts/eth/vault/ETHVaultStorage.sol
- contracts/eth/vault/IETHVault.sol
- contracts/exchanges/adapters/OneInchV4Adapter.sol
- test/vault-eth/vault-checker/vault-exchange.test.js
- test/vault-usd/vault-checker/vault-exchange.test.js
- test/vault-usd/vault-split-old-new-user.test.js
- utils/vault-utils.js
1、optimze 1inchv4（remove modify amount）
2、optimze vault burd（remove exchage）
3、modify test script
> remove vault exchage and optimze 1inch

- contracts/DependenciesPlaceholder.sol
- contracts/exchanges/adapters/ETHTestAdapter.sol
- hardhat.config.js
- package.json
- scripts/deploy.js
- utils/contract-utils-eth.js
- utils/contract-utils-usd.js
modify deploy.js adapter to test
> modify deploy.js adapter to test

- scripts/deploy.js
> modify deploy by auto script

- contracts/exchanges/adapters/OneInchV4Adapter.sol
- contracts/exchanges/adapters/ParaSwapV5Adapter.sol
- contracts/exchanges/utils/ExchangeHelpers.sol
- contracts/exchanges/utils/ParaSwapV5ActionsMixin.sol
> optimize 1inch and paraswapv5

- contracts/eth/strategies/stakewise/StakeWiseReth2Seth2500Strategy.sol
- contracts/eth/strategies/uniswapv3/ETHUniswapV3BaseStrategy.sol
- contracts/usd/strategies/uniswapv3/UniswapV3Strategy.sol
- contracts/utils/HarvestHelper.sol
- test/strategy-eth/stakewise/stake-wise-eth-seth2-3000-strategy-checker.test.js
- test/strategy-eth/stakewise/stake-wise-reth2-seth2-500-strategy-checker.test.js
- test/strategy-eth/uniswapv3/uniswapv3-reth-eth-3000-checker.test.js
- test/strategy-usd/uniswapv3/uniswapv3-busd-usdc-500-checker.test.js
- test/strategy-usd/uniswapv3/uniswapv3-dai-usdc-100-checker.test.js
- test/strategy-usd/uniswapv3/uniswapv3-dai-usdc-500-checker.test.js
- test/strategy-usd/uniswapv3/uniswapv3-dai-usdt-500-checker.test.js
- test/strategy-usd/uniswapv3/uniswapv3-gusd-usdc-3000-checker.test.js
- test/strategy-usd/uniswapv3/uniswapv3-tusd-usdc-100-checker.test.js
- test/strategy-usd/uniswapv3/uniswapv3-usdc-usdt-100-checker.test.js
- test/strategy-usd/uniswapv3/uniswapv3-usdc-usdt-500-checker.test.js
HarvestHelper add stakeWiseMerkleDistributorClaim;
V3 Ethi downsizing sync Usdi;
> HarvestHelper add stakeWiseMerkleDistributorClaim

- contracts/eth/mock/MockPriceOracleConsumer.sol
- package.json
- scripts/deploy.js
> add mock oracle

- contracts/eth/vault/ETHVault.sol
> fix report bug

- contracts/eth/strategies/aura/AuraWstETHWETHStrategy.sol
- test/exchange/exchange-aggregator-test.js
- remove aura -wsteth-weth strategy claims check.
> exchange aggregator support multi-coins.

- contracts/eth/vault/ETHVault.sol
- contracts/eth/vault/IETHVault.sol
- package.json
- test/vault-eth/vault-test.js
> add get pegtoken price

- contracts/eth/strategies/aura/AuraREthWEthStrategy.sol
- contracts/eth/strategies/aura/AuraWstETHWETHStrategy.sol
- hardhat.config.js
1、change sell aura reward coin by balancer v2
> fix sell reward bug

- package.json
> upgrade core version

- contracts/usd/strategies/convex/ib-usdc/ConvexIBUsdcStrategy.sol
- contracts/usd/strategies/convex/ib/ConvexIBUsdtStrategy.sol
> fix min redeem error by check sell_floor.

- scripts/mainnet-grow.js
> fix grow script bug

- hardhat.config.js
- scripts/mainnet-grow.js
> modify blocknum and steth apr

- contracts/eth/strategies/aave/AaveWETHstETHStrategy.sol
- contracts/usd/strategies/aave/AaveLendingStEthStrategy.sol
> fix withdraw 5 error bug

- contracts/eth/strategies/aave/AaveWETHstETHStrategy.sol
- contracts/usd/strategies/aave/AaveLendingStEthStrategy.sol
- hardhat.config.js
- scripts/aave-lend-redeem-test.js
- scripts/mock-lidoOracle.js
1、fix unknown error
2、optimze gas
> fix unknown error bug and optimize gas

- contracts/eth/strategies/aave/AaveWETHstETHStrategy.sol
- contracts/usd/strategies/aave/AaveLendingStEthStrategy.sol
- scripts/aave-lend-redeem-test.js
> optimize gas

- contracts/usd/strategies/aave/AaveLendingStEthStrategy.sol
- scripts/aave-lend-redeem-test.js
> fix rebalance bug

- config/strategy-eth/strategy-config-eth-dforce.js
- config/strategy-eth/strategy-config-eth.js
- config/strategy-usd/strategy-config-usd-dforce.js
- config/strategy-usd/strategy-config-usd.js
- contracts/eth/enums/ProtocolEnum.sol
- contracts/eth/strategies/dforce/ETHDForceRevolvingLoanStrategy.sol
- contracts/external/dforce/DFiToken.sol
- contracts/external/dforce/IDForceController.sol
- contracts/external/dforce/IDForcePriceModel.sol
- contracts/external/dforce/IDForcePriceOracle.sol
- contracts/mock/MockPriceModel.sol
- contracts/usd/strategies/dforce/DForceRevolvingLoanStrategy.sol
- hardhat.config.js
- scripts/aave-lend-redeem-test.js
- scripts/deploy-test.js
- scripts/mock-lidoOracle.js
- test/strategy-eth/dforce/dforce-revolving-loan-eth-strategy-checker.test.js
- test/strategy-eth/strategy-checker.js
- test/strategy-usd/dforce/dforce-revolving-loan-dai-checker.test.js
- test/strategy-usd/dforce/dforce-revolving-loan-usdc-checker.test.js
- test/strategy-usd/dforce/dforce-revolving-loan-usdt-checker.test.js
- test/strategy-usd/strategy-checker.js
add dforce revolving loan (dai/usdc/usdt)
> add dforce revelving loan

- config/strategy-eth/strategy-config-eth-dforce.js
- config/strategy-usd/strategy-config-usd-dforce.js
- contracts/eth/strategies/dforce/ETHDForceRevolvingLoanStrategy.sol
- contracts/external/euler/IEulerDToken.sol
- contracts/external/euler/IEulerEToken.sol
- contracts/external/euler/IEulerMarkets.sol
- contracts/usd/strategies/dforce/DForceRevolvingLoanStrategy.sol
- contracts/usd/strategies/euler/EulerRevolvingLoanStrategy.sol
- test/strategy-eth/dforce/dforce-revolving-loan-eth-strategy-checker.test.js
- test/strategy-eth/strategy-checker.js
- test/strategy-usd/dforce/dforce-revolving-loan-dai-checker.test.js
- test/strategy-usd/dforce/dforce-revolving-loan-usdc-checker.test.js
- test/strategy-usd/dforce/dforce-revolving-loan-usdt-checker.test.js
optimize gas by use euler flashloan
> optimize gas use euler flashloan

- config/strategy-usd/strategy-config-usd.js
- contracts/eth/enums/ProtocolEnum.sol
- contracts/eth/strategies/dforce/ETHDForceRevolvingLoanStrategy.sol
- contracts/usd/enums/ProtocolEnum.sol
- contracts/usd/strategies/dforce/DForceRevolvingLoanStrategy.sol
- contracts/usd/strategies/euler/EulerRevolvingLoanStrategy.sol
> fix deleverage bug

- .github/workflows/testcases.yml
1. github action node version setting
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblCtBZFMOdx67gt&view=vewHxmlOEQ&record=recVYzw1qn&field=fldSMld39s
> chore: github action script update

- config/strategy-eth/strategy-config-eth-euler.js
- config/strategy-eth/strategy-config-eth.js
- config/strategy-usd/strategy-config-usd-euler.js
- config/strategy-usd/strategy-config-usd.js
- contracts/eth/strategies/dforce/ETHDForceRevolvingLoanStrategy.sol
- contracts/eth/strategies/euler/ETHEulerRevolvingLoanStrategy.sol
- contracts/external/euler/IEulDistributor.sol
- test/strategy-eth/euler/euler-revolving-loan-weth-strategy-checker.test.js
- test/strategy-eth/euler/euler-revolving-loan-wsteth-strategy-checker.test.js
- test/strategy-usd/euler/euler-revolving-loan-dai-checker.test.js
- test/strategy-usd/euler/euler-revolving-loan-usdc-checker.test.js
- test/strategy-usd/euler/euler-revolving-loan-usdt-checker.test.js
1、eth defore modify commit 
2、add eth euler 
3、 add euler test script
> add eth euler and test script

- contracts/usd/strategies/convex/ib/ConvexIBUsdtStrategy.sol
- hardhat.config.js
- scripts/strategy-redeem.js
- scripts/upgrade-convex-ib.js
> swap ibToken with curve replace sushi.

- contracts/eth/strategies/euler/ETHEulerRevolvingLoanStrategy.sol
- contracts/usd/strategies/euler/EulerRevolvingLoanStrategy.sol
- test/strategy-eth/euler/euler-revolving-loan-weth-strategy-checker.test.js
- test/strategy-eth/euler/euler-revolving-loan-wsteth-strategy-checker.test.js
- test/strategy-eth/strategy-checker.js
- test/strategy-usd/euler/euler-revolving-loan-dai-checker.test.js
- test/strategy-usd/euler/euler-revolving-loan-usdc-checker.test.js
- test/strategy-usd/euler/euler-revolving-loan-usdt-checker.test.js
- test/strategy-usd/strategy-checker.js
> add claim and sell to vault

- contracts/usd/strategies/uniswapv3/UniswapV3Strategy.sol
- scripts/upgrade-uniswap-v3-contract.js
update UniV3 version
update upgrade-uniswap-v3-contract.js
> update UniV3 version

- config/strategy-eth/strategy-config-eth-euler.js
- config/strategy-usd/strategy-config-usd-euler.js
- contracts/eth/strategies/euler/ETHEulerRevolvingLoanStrategy.sol
- contracts/usd/strategies/euler/EulerRevolvingLoanStrategy.sol
> borrow count init by param

- config/strategy-eth/strategy-config-eth-euler.js
- config/strategy-usd/strategy-config-usd-euler.js
- contracts/eth/strategies/euler/ETHEulerRevolvingLoanStrategy.sol
- contracts/usd/strategies/euler/EulerRevolvingLoanStrategy.sol
1、usdi euler revolving loan usdc/usdt/dai
2、ethi euler revolving loan weth/wsteh
> borrow count init by param (#119)

- contracts/eth/strategies/uniswapv3/ETHUniswapV3BaseStrategy.sol
- contracts/utils/actions/UniswapV3LiquidityActionsMixin.sol
> stake wise reduction

- scripts/aave-lend-redeem-test.js
- scripts/grant.js
- scripts/upgrade-vault.js
- test/vault-eth/vault-checker/vault-remove-add-Strategy.test.js
1、 fix grant script 
2、vault upgrade script
> fix grant script and vault upgrade script
